[project]
name = "arson-analyser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tom", email = "tom.uijtdehaag@bigdatarepublic.nl" }
]
requires-python = ">=3.11"
dependencies = [
    "earthengine-api>=1.5.4",
    "geopandas>=1.0.1",
    "pandas>=2.2.3",
    "shapely>=2.0.7",
    "tqdm>=4.67.1",
]

[project.scripts]
arson-analyser = "arson_analyser:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
