### MAPKEY status
GET https://firms.modaps.eosdis.nasa.gov/mapserver/mapkey_status/?MAP_KEY={{$dotenv NASA_API_KEY}}

### Countries
GET https://firms.modaps.eosdis.nasa.gov/api/countries


### Data availability
GET https://firms.modaps.eosdis.nasa.gov/api/data_availability/csv/{{$dotenv NASA_API_KEY}}/all


### Active fire data
GET https://firms.modaps.eosdis.nasa.gov/api/country/csv/{{$dotenv NASA_API_KEY}}/VIIRS_SNPP_NRT/SDN/1/2025-03-12


### Active fire data
GET https://firms.modaps.eosdis.nasa.gov/api/country/csv/{{$dotenv NASA_API_KEY}}/VIIRS_NOAA20_NRT/SDN/1/2025-03-12


### Active fire data
GET https://firms.modaps.eosdis.nasa.gov/api/country/csv/{{$dotenv NASA_API_KEY}}/VIIRS_SNPP_NRT/SDN/1