gateways:
  duckdb:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connections
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/duckdb/#connection-options
      type: duckdb
      database: db.db
      # concurrent_tasks: 4
      # register_comments: True
      # pre_ping: False
      pretty_sql: True
      # catalogs: 
      extensions:
        - spatial
      # connector_config: 
      # token: 


default_gateway: duckdb

model_defaults:
  dialect: duckdb
  start: 2025-03-18

variables:
  # settings
  ee_project: "cir-arson-analyser"
  ee_concurrency: 50 # max number of threads used for fetching data from gee. 50 uses ~1.5GB of RAM
  country_id: "SDN"
  gadm_level: 3

  analyse_after_days: 11 # allow for at least 2 passes of sentinel 2
  analyse_retry_after_days: 21
  analyse_until_days: 60

  # validation parameters
  validation_params:
    buffer_distance: 1000
    days_around: 30
    max_cloudy_percentage: 20
    burnt_pixel_count_threshold: 10
    nbr_after_lte: -0.10
    nbr_difference_limit: 0.15

  clustering_max_date_gap: 2
  
  # paths
  path_raw_data: ../data/raw
  path_geo: ../geo
  path_areas_include: ../geo/include.gpkg
  path_areas_exclude: ../geo/exclude.gpkg
  path_gadm: ../data/gadm
  path_settlements: ../geo/settlements.gpkg
  path_output: ../output