gateways:
  duckdb:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connections
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/duckdb/#connection-options
      type: duckdb
      database: db.duckdb
      # concurrent_tasks: 4
      # register_comments: True
      # pre_ping: False
      pretty_sql: True

      extensions:
        - spatial
      # connector_config:
      # token:

default_gateway: duckdb

model_naming:
  infer_names: true

model_defaults:
  dialect: duckdb
  start: 2025-05-01

linter:
  enabled: False
  rules: "ALL"

variables:
  # settings
  ee_concurrency: 50 # max number of threads used for fetching data from gee. 50 uses ~1.5GB of RAM
  country_id: "SDN"
  gadm_level: 3

  validation_lookback: 60

  # validation parameters
  validation_params:
    buffer_distance: 1000
    days_around: 30
    max_cloudy_percentage: 20
    burnt_pixel_count_threshold: 10
    nbr_after_lte: -0.10
    nbr_difference_limit: 0.15

  # clustering
  clustering_max_date_gap: 2

  # paths
  path_gadm: ../data/gadm
  path_geonames: ../data/geonames
  path_output: ../output

  paths_areas:
    include: ../geo/include.gpkg
    exclude:
